apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-app-sa
  namespace: canary-demo
  labels:
    app: simple-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: simple-app-role
  namespace: canary-demo
  labels:
    app: simple-app
rules:
# Allow reading ConfigMaps and Secrets
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
# Allow reading Services and Endpoints for service discovery
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list", "watch"]
# Allow reading Pods for health checks and monitoring
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
# Allow creating Events for logging
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: simple-app-rolebinding
  namespace: canary-demo
  labels:
    app: simple-app
subjects:
- kind: ServiceAccount
  name: simple-app-sa
  namespace: canary-demo
roleRef:
  kind: Role
  name: simple-app-role
  apiGroup: rbac.authorization.k8s.io
---
# Additional Role for canary deployment management
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: canary-manager-role
  namespace: canary-demo
  labels:
    app: simple-app
    component: canary-manager
rules:
# Allow managing deployments for canary operations
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# Allow managing services
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# Allow reading and updating Istio resources
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices", "destinationrules", "gateways"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
# Allow reading metrics and monitoring resources
- apiGroups: ["monitoring.coreos.com"]
  resources: ["servicemonitors", "prometheusrules"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: canary-manager-sa
  namespace: canary-demo
  labels:
    app: simple-app
    component: canary-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: canary-manager-rolebinding
  namespace: canary-demo
  labels:
    app: simple-app
    component: canary-manager
subjects:
- kind: ServiceAccount
  name: canary-manager-sa
  namespace: canary-demo
roleRef:
  kind: Role
  name: canary-manager-role
  apiGroup: rbac.authorization.k8s.io